from __future__ import annotations


def build_disclaimer() -> str:
    return (
        "This is an automated early warning notification generated by the FalilaX monitoring "
        "system based on incoming water-quality data and current risk rules. It does not by "
        "itself confirm contamination, regulatory violation, or clinical exposure. All flagged "
        "readings must be reviewed and confirmed through follow-up testing, site inspection, "
        "and appropriate public health or utility procedures before final decisions are made."
    )


def normalize_risk_label(escalation_level: str) -> str:
    mapping = {
        "household_only": "Moderate",
        "site_only": "Moderate",
        "distribution_line_alert": "High",
        "central_system_alert": "High",
        "regional_emergency": "Critical",
    }
    return mapping.get(escalation_level, "Moderate")


def normalize_scope_label(escalation_level: str) -> str:
    mapping = {
        "household_only": "Household stakeholders only",
        "site_only": "Site-level stakeholders only",
        "distribution_line_alert": "Distribution-line stakeholders",
        "central_system_alert": "Central-system stakeholders",
        "regional_emergency": "Regional stakeholders and emergency contacts",
    }
    return mapping.get(escalation_level, "Site-level stakeholders only")


def build_recommended_actions(parameter_code: str, escalation_level: str) -> list[str]:
    parameter_code = parameter_code.lower()

    if parameter_code == "lead":
        base = [
            "Avoid drinking or cooking with this water until confirmation.",
            "Use bottled or alternative safe water sources if available.",
            "Arrange confirmatory testing through a certified lab.",
            "Notify facility management and local water authority if required.",
        ]
    elif parameter_code == "turbidity":
        base = [
            "Inspect treatment and filtration conditions immediately.",
            "Collect confirmatory samples for review.",
            "Notify the facility manager or system operator.",
        ]
    else:
        base = [
            "Review the flagged reading and collect a confirmatory sample.",
            "Notify the responsible site or system contact.",
            "Escalate according to FalilaX response procedures.",
        ]

    if escalation_level in {"central_system_alert", "regional_emergency"}:
        base.append("Prepare broader public communication if confirmation supports escalation.")

    return base[:4]


def build_summary(
    *,
    parameter_name: str,
    escalation_level: str,
    confidence: int | float,
) -> str:
    if escalation_level in {"household_only", "site_only"}:
        return (
            f"{parameter_name} risk appears localized to this site or institution. "
            f"Current attribution confidence is {int(confidence)}%."
        )

    if escalation_level == "distribution_line_alert":
        return (
            f"{parameter_name} risk may affect multiple connected sites on this distribution line. "
            f"Current attribution confidence is {int(confidence)}%."
        )

    if escalation_level == "central_system_alert":
        return (
            f"{parameter_name} risk may extend across the connected central water system. "
            f"Current attribution confidence is {int(confidence)}%."
        )

    return (
        f"{parameter_name} risk may have broader community implications. "
        f"Current attribution confidence is {int(confidence)}%."
    )


def build_email_alert_message(
    *,
    parameter_name: str,
    location_name: str,
    escalation_level: str,
    confidence: int | float,
) -> dict[str, str]:
    risk_level = normalize_risk_label(escalation_level)
    scope_label = normalize_scope_label(escalation_level)
    summary = build_summary(
        parameter_name=parameter_name,
        escalation_level=escalation_level,
        confidence=confidence,
    )
    actions = build_recommended_actions(parameter_name.lower(), escalation_level)
    disclaimer = build_disclaimer()

    subject = f"FalilaX Water Alert: {parameter_name.upper()} detected"

    body = (
        f"Location: {location_name}\n"
        f"Risk Level: {risk_level}\n"
        f"Confidence: {int(confidence)}%\n\n"
        f"Summary:\n{summary}\n\n"
        f"Recommended Action:\n"
        + "\n".join([f"• {action}" for action in actions])
        + f"\n\nScope:\n{scope_label}\n\n"
        f"Disclaimer:\n{disclaimer}"
    )

    return {
        "subject": subject,
        "body": body,
    }


def build_sms_alert_message(
    *,
    parameter_name: str,
    location_name: str,
    escalation_level: str,
    confidence: int | float,
) -> str:
    risk_level = normalize_risk_label(escalation_level)
    summary = build_summary(
        parameter_name=parameter_name,
        escalation_level=escalation_level,
        confidence=confidence,
    )
    disclaimer = "Automated early warning only. Confirm with follow-up testing."

    return (
        f"FalilaX Alert: {parameter_name.upper()} detected at {location_name}. "
        f"Risk: {risk_level}. Confidence: {int(confidence)}%. "
        f"{summary} {disclaimer}"
    )


def build_whatsapp_alert_message(
    *,
    parameter_name: str,
    location_name: str,
    escalation_level: str,
    confidence: int | float,
) -> str:
    risk_level = normalize_risk_label(escalation_level)
    scope_label = normalize_scope_label(escalation_level)
    summary = build_summary(
        parameter_name=parameter_name,
        escalation_level=escalation_level,
        confidence=confidence,
    )
    actions = build_recommended_actions(parameter_name.lower(), escalation_level)
    disclaimer = build_disclaimer()

    return (
        f"*FalilaX Water Alert: {parameter_name.upper()} detected*\n\n"
        f"*Location:* {location_name}\n"
        f"*Risk Level:* {risk_level}\n"
        f"*Confidence:* {int(confidence)}%\n\n"
        f"*Summary:*\n{summary}\n\n"
        f"*Recommended Action:*\n"
        + "\n".join([f"• {action}" for action in actions])
        + f"\n\n*Scope:*\n{scope_label}\n\n"
        f"*Disclaimer:*\n{disclaimer}"
    )