CHEMISTRY_PARAMETERS = [
    {
        "parameter_code": "ph",
        "display_name": "pH",
        "category": "chemical",
        "expected_unit": "pH",
        "description": "Acidity or alkalinity of water.",
        "threshold_profile": "ph",
        "regulatory_source": "EPA/WHO",
        "warn_min": 6.5,
        "warn_max": 8.5,
        "critical_min": 6.0,
        "critical_max": 9.0,
        "alerts_enabled": True,
        "is_active": True,
    },
    {
        "parameter_code": "alkalinity",
        "display_name": "Alkalinity",
        "category": "chemical",
        "expected_unit": "mg/L",
        "description": "Water's buffering capacity against pH changes.",
        "threshold_profile": "alkalinity",
        "regulatory_source": "WHO",
        "warn_min": 20.0,
        "warn_max": 200.0,
        "critical_min": 10.0,
        "critical_max": 300.0,
        "alerts_enabled": False,
        "is_active": True,
    },
    {
        "parameter_code": "hardness",
        "display_name": "Total Hardness",
        "category": "chemical",
        "expected_unit": "mg/L",
        "description": "Concentration of calcium and magnesium salts in water.",
        "threshold_profile": "hardness",
        "regulatory_source": "EPA/WHO",
        "warn_min": None,
        "warn_max": 300.0,
        "critical_min": None,
        "critical_max": 500.0,
        "alerts_enabled": False,
        "is_active": True,
    },
    {
        "parameter_code": "dissolved_oxygen",
        "display_name": "Dissolved Oxygen",
        "category": "chemical",
        "expected_unit": "mg/L",
        "description": "Amount of oxygen dissolved in water.",
        "threshold_profile": "dissolved_oxygen",
        "regulatory_source": "WHO",
        "warn_min": 4.0,
        "warn_max": None,
        "critical_min": 2.0,
        "critical_max": None,
        "alerts_enabled": False,
        "is_active": True,
    },
    {
        "parameter_code": "orp",
        "display_name": "Oxidation Reduction Potential",
        "category": "chemical",
        "expected_unit": "mV",
        "description": "Measure of the oxidizing or reducing power of water.",
        "threshold_profile": "orp",
        "regulatory_source": "Operational",
        "warn_min": 250.0,
        "warn_max": 800.0,
        "critical_min": 200.0,
        "critical_max": 900.0,
        "alerts_enabled": False,
        "is_active": True,
    },
    {
        "parameter_code": "free_chlorine",
        "display_name": "Free Chlorine",
        "category": "chemical",
        "expected_unit": "mg/L",
        "description": "Available chlorine for disinfection.",
        "threshold_profile": "free_chlorine",
        "regulatory_source": "EPA/WHO",
        "warn_min": 0.2,
        "warn_max": 4.0,
        "critical_min": 0.0,
        "critical_max": 5.0,
        "alerts_enabled": True,
        "is_active": True,
    },
    {
        "parameter_code": "total_chlorine",
        "display_name": "Total Chlorine",
        "category": "chemical",
        "expected_unit": "mg/L",
        "description": "Total chlorine residual in water.",
        "threshold_profile": "total_chlorine",
        "regulatory_source": "EPA",
        "warn_min": 0.2,
        "warn_max": 4.0,
        "critical_min": 0.0,
        "critical_max": 5.0,
        "alerts_enabled": True,
        "is_active": True,
    },
    {
        "parameter_code": "chloramine",
        "display_name": "Chloramine",
        "category": "chemical",
        "expected_unit": "mg/L",
        "description": "Combined chlorine disinfectant residual.",
        "threshold_profile": "chloramine",
        "regulatory_source": "EPA",
        "warn_min": 0.2,
        "warn_max": 3.0,
        "critical_min": 0.0,
        "critical_max": 4.0,
        "alerts_enabled": True,
        "is_active": True,
    },
    {
        "parameter_code": "fluoride",
        "display_name": "Fluoride",
        "category": "chemical",
        "expected_unit": "mg/L",
        "description": "Fluoride concentration in drinking water.",
        "threshold_profile": "fluoride",
        "regulatory_source": "EPA/WHO",
        "warn_min": None,
        "warn_max": 2.0,
        "critical_min": None,
        "critical_max": 4.0,
        "alerts_enabled": True,
        "is_active": True,
    },
    {
        "parameter_code": "cyanide",
        "display_name": "Cyanide",
        "category": "chemical",
        "expected_unit": "mg/L",
        "description": "Cyanide concentration in water.",
        "threshold_profile": "cyanide",
        "regulatory_source": "EPA/WHO",
        "warn_min": None,
        "warn_max": 0.1,
        "critical_min": None,
        "critical_max": 0.2,
        "alerts_enabled": True,
        "is_active": True,
    },
]