DISINFECTANT_PARAMETERS = [
    {
        "parameter_code": "free_chlorine_mg_l",
        "display_name": "Free Chlorine",
        "category": "disinfectant",
        "expected_unit": "mg/L",
        "description": "Available free chlorine residual in water.",
        "threshold_profile": "free_chlorine_mg_l",
        "regulatory_source": "EPA/WHO",
        "warn_min": 0.2,
        "warn_max": 4.0,
        "critical_min": 0.0,
        "critical_max": 5.0,
        "alerts_enabled": True,
        "is_active": True,
    },
    {
        "parameter_code": "total_chlorine_mg_l",
        "display_name": "Total Chlorine",
        "category": "disinfectant",
        "expected_unit": "mg/L",
        "description": "Total chlorine residual in water.",
        "threshold_profile": "total_chlorine_mg_l",
        "regulatory_source": "EPA",
        "warn_min": 0.2,
        "warn_max": 4.0,
        "critical_min": 0.0,
        "critical_max": 5.0,
        "alerts_enabled": True,
        "is_active": True,
    },
    {
        "parameter_code": "chloramine_mg_l",
        "display_name": "Chloramine",
        "category": "disinfectant",
        "expected_unit": "mg/L",
        "description": "Combined chlorine disinfectant residual.",
        "threshold_profile": "chloramine_mg_l",
        "regulatory_source": "EPA",
        "warn_min": 0.2,
        "warn_max": 3.0,
        "critical_min": 0.0,
        "critical_max": 4.0,
        "alerts_enabled": True,
        "is_active": True,
    },
    {
        "parameter_code": "chlorine_dioxide_mg_l",
        "display_name": "Chlorine Dioxide",
        "category": "disinfectant",
        "expected_unit": "mg/L",
        "description": "Chlorine dioxide residual in water.",
        "threshold_profile": "chlorine_dioxide_mg_l",
        "regulatory_source": "EPA",
        "warn_min": 0.0,
        "warn_max": 0.6,
        "critical_min": 0.0,
        "critical_max": 0.8,
        "alerts_enabled": True,
        "is_active": True,
    },
    {
        "parameter_code": "ozone_mg_l",
        "display_name": "Ozone",
        "category": "disinfectant",
        "expected_unit": "mg/L",
        "description": "Ozone residual or applied concentration in treatment context.",
        "threshold_profile": "ozone_mg_l",
        "regulatory_source": "Operational",
        "warn_min": 0.1,
        "warn_max": 0.5,
        "critical_min": 0.0,
        "critical_max": 1.0,
        "alerts_enabled": False,
        "is_active": True,
    },
    {
        "parameter_code": "bromate_mg_l",
        "display_name": "Bromate",
        "category": "disinfectant_byproduct",
        "expected_unit": "mg/L",
        "description": "Bromate byproduct formed during ozonation.",
        "threshold_profile": "bromate_mg_l",
        "regulatory_source": "EPA/WHO",
        "warn_min": None,
        "warn_max": 0.008,
        "critical_min": None,
        "critical_max": 0.01,
        "alerts_enabled": True,
        "is_active": True,
    },
    {
        "parameter_code": "chlorite_mg_l",
        "display_name": "Chlorite",
        "category": "disinfectant_byproduct",
        "expected_unit": "mg/L",
        "description": "Chlorite byproduct associated with chlorine dioxide use.",
        "threshold_profile": "chlorite_mg_l",
        "regulatory_source": "EPA",
        "warn_min": None,
        "warn_max": 0.8,
        "critical_min": None,
        "critical_max": 1.0,
        "alerts_enabled": True,
        "is_active": True,
    },
    {
        "parameter_code": "thm_total_ug_l",
        "display_name": "Total Trihalomethanes",
        "category": "disinfectant_byproduct",
        "expected_unit": "ug/L",
        "description": "Total trihalomethanes formed during chlorination.",
        "threshold_profile": "thm_total_ug_l",
        "regulatory_source": "EPA/WHO",
        "warn_min": None,
        "warn_max": 60.0,
        "critical_min": None,
        "critical_max": 80.0,
        "alerts_enabled": True,
        "is_active": True,
    },
    {
        "parameter_code": "haa5_ug_l",
        "display_name": "Haloacetic Acids (HAA5)",
        "category": "disinfectant_byproduct",
        "expected_unit": "ug/L",
        "description": "Five haloacetic acids regulated in drinking water.",
        "threshold_profile": "haa5_ug_l",
        "regulatory_source": "EPA",
        "warn_min": None,
        "warn_max": 45.0,
        "critical_min": None,
        "critical_max": 60.0,
        "alerts_enabled": True,
        "is_active": True,
    },
]