EMERGING_CONTAMINANT_PARAMETERS = [
    {
        "parameter_code": "microplastics_count_l",
        "display_name": "Microplastics",
        "category": "emerging_contaminant",
        "expected_unit": "count/L",
        "description": "Microplastic particle count in water.",
        "threshold_profile": "microplastics_count_l",
        "regulatory_source": "Emerging",
        "warn_min": None,
        "warn_max": 100.0,
        "critical_min": None,
        "critical_max": 500.0,
        "alerts_enabled": False,
        "is_active": True,
    },
    {
        "parameter_code": "bisphenol_a_ug_l",
        "display_name": "Bisphenol A",
        "category": "emerging_contaminant",
        "expected_unit": "ug/L",
        "description": "Plastic-associated endocrine disrupting compound.",
        "threshold_profile": "bisphenol_a_ug_l",
        "regulatory_source": "WHO",
        "warn_min": None,
        "warn_max": 1.0,
        "critical_min": None,
        "critical_max": 2.0,
        "alerts_enabled": True,
        "is_active": True,
    },
    {
        "parameter_code": "triclosan_ug_l",
        "display_name": "Triclosan",
        "category": "emerging_contaminant",
        "expected_unit": "ug/L",
        "description": "Antimicrobial personal care product residue.",
        "threshold_profile": "triclosan_ug_l",
        "regulatory_source": "Emerging",
        "warn_min": None,
        "warn_max": 5.0,
        "critical_min": None,
        "critical_max": 10.0,
        "alerts_enabled": True,
        "is_active": True,
    },
    {
        "parameter_code": "ibuprofen_ug_l",
        "display_name": "Ibuprofen",
        "category": "emerging_contaminant",
        "expected_unit": "ug/L",
        "description": "Pharmaceutical residue in water.",
        "threshold_profile": "ibuprofen_ug_l",
        "regulatory_source": "Emerging",
        "warn_min": None,
        "warn_max": 10.0,
        "critical_min": None,
        "critical_max": 50.0,
        "alerts_enabled": False,
        "is_active": True,
    },
    {
        "parameter_code": "acetaminophen_ug_l",
        "display_name": "Acetaminophen",
        "category": "emerging_contaminant",
        "expected_unit": "ug/L",
        "description": "Pharmaceutical residue in water systems.",
        "threshold_profile": "acetaminophen_ug_l",
        "regulatory_source": "Emerging",
        "warn_min": None,
        "warn_max": 10.0,
        "critical_min": None,
        "critical_max": 50.0,
        "alerts_enabled": False,
        "is_active": True,
    },
    {
        "parameter_code": "diclofenac_ug_l",
        "display_name": "Diclofenac",
        "category": "emerging_contaminant",
        "expected_unit": "ug/L",
        "description": "Anti-inflammatory pharmaceutical residue.",
        "threshold_profile": "diclofenac_ug_l",
        "regulatory_source": "WHO",
        "warn_min": None,
        "warn_max": 0.5,
        "critical_min": None,
        "critical_max": 1.0,
        "alerts_enabled": False,
        "is_active": True,
    },
    {
        "parameter_code": "estradiol_ng_l",
        "display_name": "Estradiol",
        "category": "emerging_contaminant",
        "expected_unit": "ng/L",
        "description": "Hormonal endocrine-disrupting compound.",
        "threshold_profile": "estradiol_ng_l",
        "regulatory_source": "Emerging",
        "warn_min": None,
        "warn_max": 1.0,
        "critical_min": None,
        "critical_max": 5.0,
        "alerts_enabled": False,
        "is_active": True,
    },
    {
        "parameter_code": "nonylphenol_ug_l",
        "display_name": "Nonylphenol",
        "category": "emerging_contaminant",
        "expected_unit": "ug/L",
        "description": "Industrial surfactant breakdown product.",
        "threshold_profile": "nonylphenol_ug_l",
        "regulatory_source": "WHO",
        "warn_min": None,
        "warn_max": 0.2,
        "critical_min": None,
        "critical_max": 0.3,
        "alerts_enabled": True,
        "is_active": True,
    },
]