HEAVY_METAL_PARAMETERS = [
    {
        "parameter_code": "lead_ppb",
        "display_name": "Lead",
        "category": "heavy_metal",
        "expected_unit": "ppb",
        "description": "Lead concentration in water.",
        "threshold_profile": "lead_ppb",
        "regulatory_source": "EPA/WHO",
        "warn_min": None,
        "warn_max": 10.0,
        "critical_min": None,
        "critical_max": 15.0,
        "alerts_enabled": True,
        "is_active": True,
    },
    {
        "parameter_code": "arsenic_ppb",
        "display_name": "Arsenic",
        "category": "heavy_metal",
        "expected_unit": "ppb",
        "description": "Arsenic concentration in water.",
        "threshold_profile": "arsenic_ppb",
        "regulatory_source": "EPA/WHO",
        "warn_min": None,
        "warn_max": 8.0,
        "critical_min": None,
        "critical_max": 10.0,
        "alerts_enabled": True,
        "is_active": True,
    },
    {
        "parameter_code": "cadmium_ppb",
        "display_name": "Cadmium",
        "category": "heavy_metal",
        "expected_unit": "ppb",
        "description": "Cadmium concentration in water.",
        "threshold_profile": "cadmium_ppb",
        "regulatory_source": "EPA/WHO",
        "warn_min": None,
        "warn_max": 4.0,
        "critical_min": None,
        "critical_max": 5.0,
        "alerts_enabled": True,
        "is_active": True,
    },
    {
        "parameter_code": "mercury_ppb",
        "display_name": "Mercury",
        "category": "heavy_metal",
        "expected_unit": "ppb",
        "description": "Mercury concentration in water.",
        "threshold_profile": "mercury_ppb",
        "regulatory_source": "EPA/WHO",
        "warn_min": None,
        "warn_max": 1.5,
        "critical_min": None,
        "critical_max": 2.0,
        "alerts_enabled": True,
        "is_active": True,
    },
    {
        "parameter_code": "chromium_ppb",
        "display_name": "Chromium",
        "category": "heavy_metal",
        "expected_unit": "ppb",
        "description": "Chromium concentration in water.",
        "threshold_profile": "chromium_ppb",
        "regulatory_source": "EPA/WHO",
        "warn_min": None,
        "warn_max": 80.0,
        "critical_min": None,
        "critical_max": 100.0,
        "alerts_enabled": True,
        "is_active": True,
    },
    {
        "parameter_code": "copper_ppb",
        "display_name": "Copper",
        "category": "heavy_metal",
        "expected_unit": "ppb",
        "description": "Copper concentration in water.",
        "threshold_profile": "copper_ppb",
        "regulatory_source": "EPA/WHO",
        "warn_min": None,
        "warn_max": 1000.0,
        "critical_min": None,
        "critical_max": 1300.0,
        "alerts_enabled": True,
        "is_active": True,
    },
    {
        "parameter_code": "zinc_ppb",
        "display_name": "Zinc",
        "category": "heavy_metal",
        "expected_unit": "ppb",
        "description": "Zinc concentration in water.",
        "threshold_profile": "zinc_ppb",
        "regulatory_source": "WHO",
        "warn_min": None,
        "warn_max": 3000.0,
        "critical_min": None,
        "critical_max": 5000.0,
        "alerts_enabled": False,
        "is_active": True,
    },
    {
        "parameter_code": "iron_mg_l",
        "display_name": "Iron",
        "category": "heavy_metal",
        "expected_unit": "mg/L",
        "description": "Iron concentration in water.",
        "threshold_profile": "iron_mg_l",
        "regulatory_source": "EPA/WHO",
        "warn_min": None,
        "warn_max": 0.3,
        "critical_min": None,
        "critical_max": 1.0,
        "alerts_enabled": False,
        "is_active": True,
    },
    {
        "parameter_code": "manganese_mg_l",
        "display_name": "Manganese",
        "category": "heavy_metal",
        "expected_unit": "mg/L",
        "description": "Manganese concentration in water.",
        "threshold_profile": "manganese_mg_l",
        "regulatory_source": "EPA/WHO",
        "warn_min": None,
        "warn_max": 0.05,
        "critical_min": None,
        "critical_max": 0.3,
        "alerts_enabled": False,
        "is_active": True,
    },
]