INDUSTRIAL_CHEMICAL_PARAMETERS = [
    {
        "parameter_code": "ammonium_mg_l",
        "display_name": "Ammonium",
        "category": "industrial_chemical",
        "expected_unit": "mg/L",
        "description": "Ammonium concentration in water, often linked to wastewater or industrial discharge.",
        "threshold_profile": "ammonium_mg_l",
        "regulatory_source": "WHO",
        "warn_min": None,
        "warn_max": 1.5,
        "critical_min": None,
        "critical_max": 3.0,
        "alerts_enabled": True,
        "is_active": True,
    },
    {
        "parameter_code": "phenol_ug_l",
        "display_name": "Phenol",
        "category": "industrial_chemical",
        "expected_unit": "ug/L",
        "description": "Phenolic compounds associated with industrial contamination.",
        "threshold_profile": "phenol_ug_l",
        "regulatory_source": "WHO",
        "warn_min": None,
        "warn_max": 1.0,
        "critical_min": None,
        "critical_max": 2.0,
        "alerts_enabled": True,
        "is_active": True,
    },
    {
        "parameter_code": "formaldehyde_ug_l",
        "display_name": "Formaldehyde",
        "category": "industrial_chemical",
        "expected_unit": "ug/L",
        "description": "Industrial and manufacturing contaminant in water.",
        "threshold_profile": "formaldehyde_ug_l",
        "regulatory_source": "WHO",
        "warn_min": None,
        "warn_max": 700.0,
        "critical_min": None,
        "critical_max": 900.0,
        "alerts_enabled": True,
        "is_active": True,
    },
    {
        "parameter_code": "acrylamide_ug_l",
        "display_name": "Acrylamide",
        "category": "industrial_chemical",
        "expected_unit": "ug/L",
        "description": "Industrial polymer-related contaminant.",
        "threshold_profile": "acrylamide_ug_l",
        "regulatory_source": "WHO",
        "warn_min": None,
        "warn_max": 0.4,
        "critical_min": None,
        "critical_max": 0.5,
        "alerts_enabled": True,
        "is_active": True,
    },
    {
        "parameter_code": "epichlorohydrin_ug_l",
        "display_name": "Epichlorohydrin",
        "category": "industrial_chemical",
        "expected_unit": "ug/L",
        "description": "Industrial contaminant associated with resins and polymers.",
        "threshold_profile": "epichlorohydrin_ug_l",
        "regulatory_source": "WHO",
        "warn_min": None,
        "warn_max": 0.3,
        "critical_min": None,
        "critical_max": 0.4,
        "alerts_enabled": True,
        "is_active": True,
    },
    {
        "parameter_code": "aniline_ug_l",
        "display_name": "Aniline",
        "category": "industrial_chemical",
        "expected_unit": "ug/L",
        "description": "Industrial aromatic amine contaminant.",
        "threshold_profile": "aniline_ug_l",
        "regulatory_source": "WHO",
        "warn_min": None,
        "warn_max": 8.0,
        "critical_min": None,
        "critical_max": 10.0,
        "alerts_enabled": True,
        "is_active": True,
    },
    {
        "parameter_code": "cyanide_free_mg_l",
        "display_name": "Free Cyanide",
        "category": "industrial_chemical",
        "expected_unit": "mg/L",
        "description": "Free cyanide associated with mining and industrial pollution.",
        "threshold_profile": "cyanide_free_mg_l",
        "regulatory_source": "EPA/WHO",
        "warn_min": None,
        "warn_max": 0.1,
        "critical_min": None,
        "critical_max": 0.2,
        "alerts_enabled": True,
        "is_active": True,
    },
    {
        "parameter_code": "sulfide_mg_l",
        "display_name": "Sulfide",
        "category": "industrial_chemical",
        "expected_unit": "mg/L",
        "description": "Reduced sulfur compound linked to industrial and anaerobic contamination.",
        "threshold_profile": "sulfide_mg_l",
        "regulatory_source": "Operational",
        "warn_min": None,
        "warn_max": 0.05,
        "critical_min": None,
        "critical_max": 0.1,
        "alerts_enabled": True,
        "is_active": True,
    },
    {
        "parameter_code": "detergents_mg_l",
        "display_name": "Detergents",
        "category": "industrial_chemical",
        "expected_unit": "mg/L",
        "description": "Synthetic detergent residues in water.",
        "threshold_profile": "detergents_mg_l",
        "regulatory_source": "WHO",
        "warn_min": None,
        "warn_max": 0.2,
        "critical_min": None,
        "critical_max": 0.5,
        "alerts_enabled": False,
        "is_active": True,
    },
]