ION_PARAMETERS = [
    {
        "parameter_code": "chloride",
        "display_name": "Chloride",
        "category": "ion",
        "expected_unit": "mg/L",
        "description": "Chloride concentration in water.",
        "threshold_profile": "chloride",
        "regulatory_source": "EPA/WHO",
        "warn_min": None,
        "warn_max": 250.0,
        "critical_min": None,
        "critical_max": 500.0,
        "alerts_enabled": False,
        "is_active": True,
    },
    {
        "parameter_code": "sulfate",
        "display_name": "Sulfate",
        "category": "ion",
        "expected_unit": "mg/L",
        "description": "Sulfate concentration in water.",
        "threshold_profile": "sulfate",
        "regulatory_source": "EPA/WHO",
        "warn_min": None,
        "warn_max": 250.0,
        "critical_min": None,
        "critical_max": 500.0,
        "alerts_enabled": False,
        "is_active": True,
    },
    {
        "parameter_code": "bicarbonate",
        "display_name": "Bicarbonate",
        "category": "ion",
        "expected_unit": "mg/L",
        "description": "Bicarbonate concentration contributing to alkalinity.",
        "threshold_profile": "bicarbonate",
        "regulatory_source": "WHO",
        "warn_min": None,
        "warn_max": 300.0,
        "critical_min": None,
        "critical_max": 500.0,
        "alerts_enabled": False,
        "is_active": True,
    },
    {
        "parameter_code": "carbonate",
        "display_name": "Carbonate",
        "category": "ion",
        "expected_unit": "mg/L",
        "description": "Carbonate concentration in water.",
        "threshold_profile": "carbonate",
        "regulatory_source": "WHO",
        "warn_min": None,
        "warn_max": 100.0,
        "critical_min": None,
        "critical_max": 200.0,
        "alerts_enabled": False,
        "is_active": True,
    },
    {
        "parameter_code": "calcium",
        "display_name": "Calcium",
        "category": "ion",
        "expected_unit": "mg/L",
        "description": "Calcium ion concentration in water.",
        "threshold_profile": "calcium",
        "regulatory_source": "WHO",
        "warn_min": None,
        "warn_max": 150.0,
        "critical_min": None,
        "critical_max": 300.0,
        "alerts_enabled": False,
        "is_active": True,
    },
    {
        "parameter_code": "magnesium",
        "display_name": "Magnesium",
        "category": "ion",
        "expected_unit": "mg/L",
        "description": "Magnesium ion concentration in water.",
        "threshold_profile": "magnesium",
        "regulatory_source": "WHO",
        "warn_min": None,
        "warn_max": 100.0,
        "critical_min": None,
        "critical_max": 150.0,
        "alerts_enabled": False,
        "is_active": True,
    },
    {
        "parameter_code": "sodium",
        "display_name": "Sodium",
        "category": "ion",
        "expected_unit": "mg/L",
        "description": "Sodium concentration in water.",
        "threshold_profile": "sodium",
        "regulatory_source": "WHO",
        "warn_min": None,
        "warn_max": 200.0,
        "critical_min": None,
        "critical_max": 400.0,
        "alerts_enabled": False,
        "is_active": True,
    },
    {
        "parameter_code": "potassium",
        "display_name": "Potassium",
        "category": "ion",
        "expected_unit": "mg/L",
        "description": "Potassium concentration in water.",
        "threshold_profile": "potassium",
        "regulatory_source": "WHO",
        "warn_min": None,
        "warn_max": 20.0,
        "critical_min": None,
        "critical_max": 50.0,
        "alerts_enabled": False,
        "is_active": True,
    },
]