MICROBIAL_TOXIN_PARAMETERS = [
    {
        "parameter_code": "microcystin_ug_l",
        "display_name": "Microcystin",
        "category": "microbial_toxin",
        "expected_unit": "ug/L",
        "description": "Cyanobacterial toxin commonly associated with harmful algal blooms.",
        "threshold_profile": "microcystin_ug_l",
        "regulatory_source": "WHO/EPA",
        "warn_min": None,
        "warn_max": 0.8,
        "critical_min": None,
        "critical_max": 1.0,
        "alerts_enabled": True,
        "is_active": True,
    },
    {
        "parameter_code": "anatoxin_a_ug_l",
        "display_name": "Anatoxin-a",
        "category": "microbial_toxin",
        "expected_unit": "ug/L",
        "description": "Neurotoxic cyanobacterial toxin in freshwater systems.",
        "threshold_profile": "anatoxin_a_ug_l",
        "regulatory_source": "WHO",
        "warn_min": None,
        "warn_max": 2.5,
        "critical_min": None,
        "critical_max": 3.0,
        "alerts_enabled": True,
        "is_active": True,
    },
    {
        "parameter_code": "cylindrospermopsin_ug_l",
        "display_name": "Cylindrospermopsin",
        "category": "microbial_toxin",
        "expected_unit": "ug/L",
        "description": "Cyanobacterial toxin associated with liver and kidney effects.",
        "threshold_profile": "cylindrospermopsin_ug_l",
        "regulatory_source": "WHO",
        "warn_min": None,
        "warn_max": 0.7,
        "critical_min": None,
        "critical_max": 1.0,
        "alerts_enabled": True,
        "is_active": True,
    },
    {
        "parameter_code": "saxitoxin_ug_l",
        "display_name": "Saxitoxin",
        "category": "microbial_toxin",
        "expected_unit": "ug/L",
        "description": "Paralytic shellfish toxin that may occur in contaminated water bodies.",
        "threshold_profile": "saxitoxin_ug_l",
        "regulatory_source": "WHO",
        "warn_min": None,
        "warn_max": 2.0,
        "critical_min": None,
        "critical_max": 3.0,
        "alerts_enabled": True,
        "is_active": True,
    },
    {
        "parameter_code": "nodularin_ug_l",
        "display_name": "Nodularin",
        "category": "microbial_toxin",
        "expected_unit": "ug/L",
        "description": "Hepatotoxic cyanobacterial toxin found in brackish and freshwater systems.",
        "threshold_profile": "nodularin_ug_l",
        "regulatory_source": "WHO",
        "warn_min": None,
        "warn_max": 0.8,
        "critical_min": None,
        "critical_max": 1.0,
        "alerts_enabled": True,
        "is_active": True,
    },
    {
        "parameter_code": "domoic_acid_ug_l",
        "display_name": "Domoic Acid",
        "category": "microbial_toxin",
        "expected_unit": "ug/L",
        "description": "Neurotoxin associated with certain algal contamination events.",
        "threshold_profile": "domoic_acid_ug_l",
        "regulatory_source": "WHO",
        "warn_min": None,
        "warn_max": 8.0,
        "critical_min": None,
        "critical_max": 10.0,
        "alerts_enabled": True,
        "is_active": True,
    },
]