MICROBIOLOGY_PARAMETERS = [

{
"parameter_code": "total_coliform_cfu",
"display_name": "Total Coliform",
"category": "microbiology",
"expected_unit": "CFU/100mL",
"description": "Indicator bacteria used to assess sanitary quality of water.",
"threshold_profile": "total_coliform",
"regulatory_source": "EPA/WHO",
"warn_min": None,
"warn_max": 1,
"critical_min": None,
"critical_max": 1,
"alerts_enabled": True,
"is_active": True,
},

{
"parameter_code": "e_coli_cfu",
"display_name": "E. coli",
"category": "microbiology",
"expected_unit": "CFU/100mL",
"description": "Indicator of fecal contamination in water.",
"threshold_profile": "e_coli",
"regulatory_source": "EPA/WHO",
"warn_min": None,
"warn_max": 1,
"critical_min": None,
"critical_max": 1,
"alerts_enabled": True,
"is_active": True,
},

{
"parameter_code": "fecal_coliform_cfu",
"display_name": "Fecal Coliform",
"category": "microbiology",
"expected_unit": "CFU/100mL",
"description": "Indicator bacteria associated with fecal contamination.",
"threshold_profile": "fecal_coliform",
"regulatory_source": "WHO",
"warn_min": None,
"warn_max": 1,
"critical_min": None,
"critical_max": 1,
"alerts_enabled": True,
"is_active": True,
},

{
"parameter_code": "enterococcus_cfu",
"display_name": "Enterococcus",
"category": "microbiology",
"expected_unit": "CFU/100mL",
"description": "Indicator of fecal contamination particularly in recreational waters.",
"threshold_profile": "enterococcus",
"regulatory_source": "EPA",
"warn_min": None,
"warn_max": 30,
"critical_min": None,
"critical_max": 60,
"alerts_enabled": True,
"is_active": True,
},

{
"parameter_code": "legionella_cfu",
"display_name": "Legionella",
"category": "microbiology",
"expected_unit": "CFU/L",
"description": "Legionella bacteria associated with Legionnaires disease.",
"threshold_profile": "legionella",
"regulatory_source": "WHO",
"warn_min": None,
"warn_max": 100,
"critical_min": None,
"critical_max": 1000,
"alerts_enabled": True,
"is_active": True,
},

{
"parameter_code": "salmonella_presence",
"display_name": "Salmonella",
"category": "microbiology",
"expected_unit": "presence/absence",
"description": "Detection of Salmonella bacteria in water.",
"threshold_profile": "salmonella",
"regulatory_source": "WHO",
"warn_min": None,
"warn_max": None,
"critical_min": None,
"critical_max": None,
"alerts_enabled": True,
"is_active": True,
},

{
"parameter_code": "vibrio_cholerae_presence",
"display_name": "Vibrio cholerae",
"category": "microbiology",
"expected_unit": "presence/absence",
"description": "Detection of Vibrio cholerae pathogen.",
"threshold_profile": "vibrio_cholerae",
"regulatory_source": "WHO",
"warn_min": None,
"warn_max": None,
"critical_min": None,
"critical_max": None,
"alerts_enabled": True,
"is_active": True,
},

{
"parameter_code": "clostridium_perfringens_cfu",
"display_name": "Clostridium perfringens",
"category": "microbiology",
"expected_unit": "CFU/100mL",
"description": "Indicator of past fecal contamination.",
"threshold_profile": "clostridium_perfringens",
"regulatory_source": "WHO",
"warn_min": None,
"warn_max": 1,
"critical_min": None,
"critical_max": 1,
"alerts_enabled": True,
"is_active": True,
},

{
"parameter_code": "pseudomonas_cfu",
"display_name": "Pseudomonas",
"category": "microbiology",
"expected_unit": "CFU/100mL",
"description": "Indicator bacteria often associated with opportunistic pathogens.",
"threshold_profile": "pseudomonas",
"regulatory_source": "WHO",
"warn_min": None,
"warn_max": 10,
"critical_min": None,
"critical_max": 100,
"alerts_enabled": True,
"is_active": True,
},

]