NUTRIENT_SPECIES_PARAMETERS = [
    {
        "parameter_code": "nitrate_mg_l",
        "display_name": "Nitrate",
        "category": "nutrient",
        "expected_unit": "mg/L",
        "description": "Nitrate concentration in water.",
        "threshold_profile": "nitrate_mg_l",
        "regulatory_source": "EPA/WHO",
        "warn_min": None,
        "warn_max": 8.0,
        "critical_min": None,
        "critical_max": 10.0,
        "alerts_enabled": True,
        "is_active": True,
    },
    {
        "parameter_code": "nitrite_mg_l",
        "display_name": "Nitrite",
        "category": "nutrient",
        "expected_unit": "mg/L",
        "description": "Nitrite concentration in water.",
        "threshold_profile": "nitrite_mg_l",
        "regulatory_source": "EPA/WHO",
        "warn_min": None,
        "warn_max": 0.8,
        "critical_min": None,
        "critical_max": 1.0,
        "alerts_enabled": True,
        "is_active": True,
    },
    {
        "parameter_code": "ammonia_mg_l",
        "display_name": "Ammonia",
        "category": "nutrient",
        "expected_unit": "mg/L",
        "description": "Ammonia nitrogen concentration.",
        "threshold_profile": "ammonia_mg_l",
        "regulatory_source": "WHO",
        "warn_min": None,
        "warn_max": 1.5,
        "critical_min": None,
        "critical_max": 3.0,
        "alerts_enabled": True,
        "is_active": True,
    },
    {
        "parameter_code": "total_nitrogen_mg_l",
        "display_name": "Total Nitrogen",
        "category": "nutrient",
        "expected_unit": "mg/L",
        "description": "Combined nitrogen species in water.",
        "threshold_profile": "total_nitrogen_mg_l",
        "regulatory_source": "Environmental",
        "warn_min": None,
        "warn_max": 5.0,
        "critical_min": None,
        "critical_max": 10.0,
        "alerts_enabled": False,
        "is_active": True,
    },
    {
        "parameter_code": "orthophosphate_mg_l",
        "display_name": "Orthophosphate",
        "category": "nutrient",
        "expected_unit": "mg/L",
        "description": "Reactive phosphate concentration.",
        "threshold_profile": "orthophosphate_mg_l",
        "regulatory_source": "Environmental",
        "warn_min": None,
        "warn_max": 0.1,
        "critical_min": None,
        "critical_max": 0.3,
        "alerts_enabled": False,
        "is_active": True,
    },
    {
        "parameter_code": "total_phosphorus_mg_l",
        "display_name": "Total Phosphorus",
        "category": "nutrient",
        "expected_unit": "mg/L",
        "description": "Total phosphorus concentration.",
        "threshold_profile": "total_phosphorus_mg_l",
        "regulatory_source": "Environmental",
        "warn_min": None,
        "warn_max": 0.2,
        "critical_min": None,
        "critical_max": 0.5,
        "alerts_enabled": False,
        "is_active": True,
    },
]