NUTRIENT_PARAMETERS = [
    {
        "parameter_code": "ammonia",
        "display_name": "Ammonia",
        "category": "nutrient",
        "expected_unit": "mg/L",
        "description": "Ammonia concentration indicating possible organic contamination.",
        "threshold_profile": "ammonia",
        "regulatory_source": "WHO",
        "warn_min": None,
        "warn_max": 1.5,
        "critical_min": None,
        "critical_max": 3.0,
        "alerts_enabled": True,
        "is_active": True,
    },
    {
        "parameter_code": "nitrate",
        "display_name": "Nitrate",
        "category": "nutrient",
        "expected_unit": "mg/L",
        "description": "Nitrate concentration in drinking water.",
        "threshold_profile": "nitrate",
        "regulatory_source": "EPA/WHO",
        "warn_min": None,
        "warn_max": 10.0,
        "critical_min": None,
        "critical_max": 50.0,
        "alerts_enabled": True,
        "is_active": True,
    },
    {
        "parameter_code": "nitrite",
        "display_name": "Nitrite",
        "category": "nutrient",
        "expected_unit": "mg/L",
        "description": "Nitrite concentration indicating microbial activity or contamination.",
        "threshold_profile": "nitrite",
        "regulatory_source": "EPA/WHO",
        "warn_min": None,
        "warn_max": 1.0,
        "critical_min": None,
        "critical_max": 3.0,
        "alerts_enabled": True,
        "is_active": True,
    },
    {
        "parameter_code": "total_nitrogen",
        "display_name": "Total Nitrogen",
        "category": "nutrient",
        "expected_unit": "mg/L",
        "description": "Combined nitrogen content in water.",
        "threshold_profile": "total_nitrogen",
        "regulatory_source": "Environmental",
        "warn_min": None,
        "warn_max": 10.0,
        "critical_min": None,
        "critical_max": 20.0,
        "alerts_enabled": False,
        "is_active": True,
    },
    {
        "parameter_code": "phosphate",
        "display_name": "Phosphate",
        "category": "nutrient",
        "expected_unit": "mg/L",
        "description": "Phosphate concentration contributing to eutrophication.",
        "threshold_profile": "phosphate",
        "regulatory_source": "WHO",
        "warn_min": None,
        "warn_max": 0.5,
        "critical_min": None,
        "critical_max": 1.0,
        "alerts_enabled": False,
        "is_active": True,
    },
    {
        "parameter_code": "total_phosphorus",
        "display_name": "Total Phosphorus",
        "category": "nutrient",
        "expected_unit": "mg/L",
        "description": "Total phosphorus concentration in water.",
        "threshold_profile": "total_phosphorus",
        "regulatory_source": "Environmental",
        "warn_min": None,
        "warn_max": 0.3,
        "critical_min": None,
        "critical_max": 1.0,
        "alerts_enabled": False,
        "is_active": True,
    },
    {
        "parameter_code": "organic_nitrogen",
        "display_name": "Organic Nitrogen",
        "category": "nutrient",
        "expected_unit": "mg/L",
        "description": "Nitrogen bound in organic compounds.",
        "threshold_profile": "organic_nitrogen",
        "regulatory_source": "Environmental",
        "warn_min": None,
        "warn_max": 5.0,
        "critical_min": None,
        "critical_max": 10.0,
        "alerts_enabled": False,
        "is_active": True,
    },
]