OPERATIONAL_PARAMETERS = [
    {
        "parameter_code": "flow_rate_l_min",
        "display_name": "Flow Rate",
        "category": "operational",
        "expected_unit": "L/min",
        "description": "Water flow rate through a distribution or treatment point.",
        "threshold_profile": "flow_rate_l_min",
        "regulatory_source": "Operational",
        "warn_min": 1.0,
        "warn_max": 500.0,
        "critical_min": 0.1,
        "critical_max": 1000.0,
        "alerts_enabled": False,
        "is_active": True,
    },
    {
        "parameter_code": "pressure_psi",
        "display_name": "Pressure",
        "category": "operational",
        "expected_unit": "psi",
        "description": "Water pressure in the system.",
        "threshold_profile": "pressure_psi",
        "regulatory_source": "Operational",
        "warn_min": 20.0,
        "warn_max": 80.0,
        "critical_min": 10.0,
        "critical_max": 100.0,
        "alerts_enabled": True,
        "is_active": True,
    },
    {
        "parameter_code": "tank_level_percent",
        "display_name": "Tank Level",
        "category": "operational",
        "expected_unit": "%",
        "description": "Water storage tank fill level.",
        "threshold_profile": "tank_level_percent",
        "regulatory_source": "Operational",
        "warn_min": 20.0,
        "warn_max": 95.0,
        "critical_min": 10.0,
        "critical_max": 100.0,
        "alerts_enabled": False,
        "is_active": True,
    },
    {
        "parameter_code": "residual_time_min",
        "display_name": "Residual Contact Time",
        "category": "operational",
        "expected_unit": "min",
        "description": "Estimated disinfectant contact time.",
        "threshold_profile": "residual_time_min",
        "regulatory_source": "Operational",
        "warn_min": 15.0,
        "warn_max": 120.0,
        "critical_min": 5.0,
        "critical_max": 240.0,
        "alerts_enabled": False,
        "is_active": True,
    },
    {
        "parameter_code": "filter_headloss_m",
        "display_name": "Filter Headloss",
        "category": "operational",
        "expected_unit": "m",
        "description": "Headloss across a filter bed indicating clogging or fouling.",
        "threshold_profile": "filter_headloss_m",
        "regulatory_source": "Operational",
        "warn_min": None,
        "warn_max": 2.0,
        "critical_min": None,
        "critical_max": 3.0,
        "alerts_enabled": False,
        "is_active": True,
    },
    {
        "parameter_code": "pump_runtime_hr",
        "display_name": "Pump Runtime",
        "category": "operational",
        "expected_unit": "hr",
        "description": "Pump runtime over an operating window.",
        "threshold_profile": "pump_runtime_hr",
        "regulatory_source": "Operational",
        "warn_min": None,
        "warn_max": 20.0,
        "critical_min": None,
        "critical_max": 24.0,
        "alerts_enabled": False,
        "is_active": True,
    },
    {
        "parameter_code": "valve_position_percent",
        "display_name": "Valve Position",
        "category": "operational",
        "expected_unit": "%",
        "description": "Valve opening percentage in the distribution system.",
        "threshold_profile": "valve_position_percent",
        "regulatory_source": "Operational",
        "warn_min": 5.0,
        "warn_max": 95.0,
        "critical_min": 0.0,
        "critical_max": 100.0,
        "alerts_enabled": False,
        "is_active": True,
    },
    {
        "parameter_code": "energy_use_kwh",
        "display_name": "Energy Use",
        "category": "operational",
        "expected_unit": "kWh",
        "description": "Electrical energy used by treatment or pumping operations.",
        "threshold_profile": "energy_use_kwh",
        "regulatory_source": "Operational",
        "warn_min": None,
        "warn_max": 500.0,
        "critical_min": None,
        "critical_max": 1000.0,
        "alerts_enabled": False,
        "is_active": True,
    },
]