ORGANIC_CONTAMINANT_PARAMETERS = [
    {
        "parameter_code": "benzene_ug_l",
        "display_name": "Benzene",
        "category": "organic_contaminant",
        "expected_unit": "ug/L",
        "description": "Volatile organic compound associated with petroleum contamination.",
        "threshold_profile": "benzene_ug_l",
        "regulatory_source": "EPA/WHO",
        "warn_min": None,
        "warn_max": 4.0,
        "critical_min": None,
        "critical_max": 5.0,
        "alerts_enabled": True,
        "is_active": True,
    },
    {
        "parameter_code": "toluene_ug_l",
        "display_name": "Toluene",
        "category": "organic_contaminant",
        "expected_unit": "ug/L",
        "description": "Volatile organic compound found in fuels and industrial solvents.",
        "threshold_profile": "toluene_ug_l",
        "regulatory_source": "EPA/WHO",
        "warn_min": None,
        "warn_max": 700.0,
        "critical_min": None,
        "critical_max": 1000.0,
        "alerts_enabled": True,
        "is_active": True,
    },
    {
        "parameter_code": "ethylbenzene_ug_l",
        "display_name": "Ethylbenzene",
        "category": "organic_contaminant",
        "expected_unit": "ug/L",
        "description": "Organic compound associated with petroleum products.",
        "threshold_profile": "ethylbenzene_ug_l",
        "regulatory_source": "EPA/WHO",
        "warn_min": None,
        "warn_max": 500.0,
        "critical_min": None,
        "critical_max": 700.0,
        "alerts_enabled": True,
        "is_active": True,
    },
    {
        "parameter_code": "xylene_total_ug_l",
        "display_name": "Total Xylenes",
        "category": "organic_contaminant",
        "expected_unit": "ug/L",
        "description": "Combined xylene isomers in water.",
        "threshold_profile": "xylene_total_ug_l",
        "regulatory_source": "EPA/WHO",
        "warn_min": None,
        "warn_max": 8000.0,
        "critical_min": None,
        "critical_max": 10000.0,
        "alerts_enabled": True,
        "is_active": True,
    },
    {
        "parameter_code": "styrene_ug_l",
        "display_name": "Styrene",
        "category": "organic_contaminant",
        "expected_unit": "ug/L",
        "description": "Organic contaminant used in plastics manufacturing.",
        "threshold_profile": "styrene_ug_l",
        "regulatory_source": "EPA/WHO",
        "warn_min": None,
        "warn_max": 80.0,
        "critical_min": None,
        "critical_max": 100.0,
        "alerts_enabled": True,
        "is_active": True,
    },
    {
        "parameter_code": "vinyl_chloride_ug_l",
        "display_name": "Vinyl Chloride",
        "category": "organic_contaminant",
        "expected_unit": "ug/L",
        "description": "Carcinogenic organic contaminant in water.",
        "threshold_profile": "vinyl_chloride_ug_l",
        "regulatory_source": "EPA/WHO",
        "warn_min": None,
        "warn_max": 1.5,
        "critical_min": None,
        "critical_max": 2.0,
        "alerts_enabled": True,
        "is_active": True,
    },
    {
        "parameter_code": "carbon_tetrachloride_ug_l",
        "display_name": "Carbon Tetrachloride",
        "category": "organic_contaminant",
        "expected_unit": "ug/L",
        "description": "Halogenated organic solvent and drinking water contaminant.",
        "threshold_profile": "carbon_tetrachloride_ug_l",
        "regulatory_source": "EPA/WHO",
        "warn_min": None,
        "warn_max": 4.0,
        "critical_min": None,
        "critical_max": 5.0,
        "alerts_enabled": True,
        "is_active": True,
    },
    {
        "parameter_code": "trichloroethylene_ug_l",
        "display_name": "Trichloroethylene",
        "category": "organic_contaminant",
        "expected_unit": "ug/L",
        "description": "Industrial solvent and groundwater contaminant.",
        "threshold_profile": "trichloroethylene_ug_l",
        "regulatory_source": "EPA/WHO",
        "warn_min": None,
        "warn_max": 4.0,
        "critical_min": None,
        "critical_max": 5.0,
        "alerts_enabled": True,
        "is_active": True,
    },
    {
        "parameter_code": "tetrachloroethylene_ug_l",
        "display_name": "Tetrachloroethylene",
        "category": "organic_contaminant",
        "expected_unit": "ug/L",
        "description": "Dry-cleaning solvent and drinking water contaminant.",
        "threshold_profile": "tetrachloroethylene_ug_l",
        "regulatory_source": "EPA/WHO",
        "warn_min": None,
        "warn_max": 4.0,
        "critical_min": None,
        "critical_max": 5.0,
        "alerts_enabled": True,
        "is_active": True,
    },
]