PESTICIDE_PARAMETERS = [
    {
        "parameter_code": "atrazine_ug_l",
        "display_name": "Atrazine",
        "category": "pesticide",
        "expected_unit": "ug/L",
        "description": "Herbicide commonly detected in agricultural runoff.",
        "threshold_profile": "atrazine_ug_l",
        "regulatory_source": "EPA/WHO",
        "warn_min": None,
        "warn_max": 2.5,
        "critical_min": None,
        "critical_max": 3.0,
        "alerts_enabled": True,
        "is_active": True,
    },
    {
        "parameter_code": "simazine_ug_l",
        "display_name": "Simazine",
        "category": "pesticide",
        "expected_unit": "ug/L",
        "description": "Herbicide used in agriculture and vegetation control.",
        "threshold_profile": "simazine_ug_l",
        "regulatory_source": "EPA/WHO",
        "warn_min": None,
        "warn_max": 3.0,
        "critical_min": None,
        "critical_max": 4.0,
        "alerts_enabled": True,
        "is_active": True,
    },
    {
        "parameter_code": "alachlor_ug_l",
        "display_name": "Alachlor",
        "category": "pesticide",
        "expected_unit": "ug/L",
        "description": "Herbicide associated with groundwater contamination.",
        "threshold_profile": "alachlor_ug_l",
        "regulatory_source": "EPA",
        "warn_min": None,
        "warn_max": 1.5,
        "critical_min": None,
        "critical_max": 2.0,
        "alerts_enabled": True,
        "is_active": True,
    },
    {
        "parameter_code": "glyphosate_ug_l",
        "display_name": "Glyphosate",
        "category": "pesticide",
        "expected_unit": "ug/L",
        "description": "Widely used herbicide with environmental monitoring relevance.",
        "threshold_profile": "glyphosate_ug_l",
        "regulatory_source": "WHO",
        "warn_min": None,
        "warn_max": 700.0,
        "critical_min": None,
        "critical_max": 900.0,
        "alerts_enabled": True,
        "is_active": True,
    },
    {
        "parameter_code": "diuron_ug_l",
        "display_name": "Diuron",
        "category": "pesticide",
        "expected_unit": "ug/L",
        "description": "Herbicide used for weed control and often monitored in water.",
        "threshold_profile": "diuron_ug_l",
        "regulatory_source": "WHO",
        "warn_min": None,
        "warn_max": 15.0,
        "critical_min": None,
        "critical_max": 20.0,
        "alerts_enabled": True,
        "is_active": True,
    },
    {
        "parameter_code": "2_4_d_ug_l",
        "display_name": "2,4-D",
        "category": "pesticide",
        "expected_unit": "ug/L",
        "description": "Common herbicide used in agriculture and lawn care.",
        "threshold_profile": "2_4_d_ug_l",
        "regulatory_source": "EPA/WHO",
        "warn_min": None,
        "warn_max": 50.0,
        "critical_min": None,
        "critical_max": 70.0,
        "alerts_enabled": True,
        "is_active": True,
    },
    {
        "parameter_code": "lindane_ug_l",
        "display_name": "Lindane",
        "category": "pesticide",
        "expected_unit": "ug/L",
        "description": "Organochlorine pesticide monitored in drinking water.",
        "threshold_profile": "lindane_ug_l",
        "regulatory_source": "EPA/WHO",
        "warn_min": None,
        "warn_max": 0.15,
        "critical_min": None,
        "critical_max": 0.2,
        "alerts_enabled": True,
        "is_active": True,
    },
    {
        "parameter_code": "endrin_ug_l",
        "display_name": "Endrin",
        "category": "pesticide",
        "expected_unit": "ug/L",
        "description": "Persistent pesticide monitored as a toxic contaminant.",
        "threshold_profile": "endrin_ug_l",
        "regulatory_source": "EPA",
        "warn_min": None,
        "warn_max": 1.5,
        "critical_min": None,
        "critical_max": 2.0,
        "alerts_enabled": True,
        "is_active": True,
    },
]