PFAS_PARAMETERS = [

{
"parameter_code": "pfos_ng_l",
"display_name": "PFOS",
"category": "pfas",
"expected_unit": "ng/L",
"description": "Perfluorooctane sulfonate, a persistent PFAS compound.",
"threshold_profile": "pfos_ng_l",
"regulatory_source": "EPA",
"warn_min": None,
"warn_max": 3.0,
"critical_min": None,
"critical_max": 4.0,
"alerts_enabled": True,
"is_active": True,
},

{
"parameter_code": "pfoa_ng_l",
"display_name": "PFOA",
"category": "pfas",
"expected_unit": "ng/L",
"description": "Perfluorooctanoic acid, a widely studied PFAS contaminant.",
"threshold_profile": "pfoa_ng_l",
"regulatory_source": "EPA",
"warn_min": None,
"warn_max": 3.0,
"critical_min": None,
"critical_max": 4.0,
"alerts_enabled": True,
"is_active": True,
},

{
"parameter_code": "pfhx_s_ng_l",
"display_name": "PFHxS",
"category": "pfas",
"expected_unit": "ng/L",
"description": "Perfluorohexane sulfonate PFAS compound.",
"threshold_profile": "pfhx_s_ng_l",
"regulatory_source": "EPA",
"warn_min": None,
"warn_max": 8.0,
"critical_min": None,
"critical_max": 10.0,
"alerts_enabled": True,
"is_active": True,
},

{
"parameter_code": "pfna_ng_l",
"display_name": "PFNA",
"category": "pfas",
"expected_unit": "ng/L",
"description": "Perfluorononanoic acid PFAS compound.",
"threshold_profile": "pfna_ng_l",
"regulatory_source": "EPA",
"warn_min": None,
"warn_max": 8.0,
"critical_min": None,
"critical_max": 10.0,
"alerts_enabled": True,
"is_active": True,
},

{
"parameter_code": "pfbs_ng_l",
"display_name": "PFBS",
"category": "pfas",
"expected_unit": "ng/L",
"description": "Perfluorobutane sulfonate PFAS compound.",
"threshold_profile": "pfbs_ng_l",
"regulatory_source": "EPA",
"warn_min": None,
"warn_max": 1500.0,
"critical_min": None,
"critical_max": 2000.0,
"alerts_enabled": True,
"is_active": True,
},

{
"parameter_code": "pfas_total_ng_l",
"display_name": "Total PFAS",
"category": "pfas",
"expected_unit": "ng/L",
"description": "Combined PFAS concentration across monitored compounds.",
"threshold_profile": "pfas_total_ng_l",
"regulatory_source": "EPA/WHO",
"warn_min": None,
"warn_max": 10.0,
"critical_min": None,
"critical_max": 20.0,
"alerts_enabled": True,
"is_active": True,
},

]