PHYSICAL_PARAMETERS = [
    {
        "parameter_code": "turbidity",
        "display_name": "Turbidity",
        "category": "physical",
        "expected_unit": "NTU",
        "description": "Measure of water clarity based on suspended particles.",
        "threshold_profile": "turbidity",
        "regulatory_source": "EPA/WHO",
        "warn_min": None,
        "warn_max": 5.0,
        "critical_min": None,
        "critical_max": 10.0,
        "alerts_enabled": True,
        "is_active": True,
    },
    {
        "parameter_code": "temperature",
        "display_name": "Water Temperature",
        "category": "physical",
        "expected_unit": "C",
        "description": "Temperature of water at the point of measurement.",
        "threshold_profile": "temperature",
        "regulatory_source": "EPA/WHO",
        "warn_min": None,
        "warn_max": 30.0,
        "critical_min": None,
        "critical_max": 35.0,
        "alerts_enabled": False,
        "is_active": True,
    },
    {
        "parameter_code": "conductivity",
        "display_name": "Electrical Conductivity",
        "category": "physical",
        "expected_unit": "uS/cm",
        "description": "Measure of water’s ability to conduct electricity.",
        "threshold_profile": "conductivity",
        "regulatory_source": "EPA/WHO",
        "warn_min": None,
        "warn_max": 1500.0,
        "critical_min": None,
        "critical_max": 2500.0,
        "alerts_enabled": False,
        "is_active": True,
    },
    {
        "parameter_code": "tds",
        "display_name": "Total Dissolved Solids",
        "category": "physical",
        "expected_unit": "mg/L",
        "description": "Combined content of all inorganic and organic dissolved substances.",
        "threshold_profile": "tds",
        "regulatory_source": "EPA/WHO",
        "warn_min": None,
        "warn_max": 500.0,
        "critical_min": None,
        "critical_max": 1000.0,
        "alerts_enabled": False,
        "is_active": True,
    },
    {
        "parameter_code": "salinity",
        "display_name": "Salinity",
        "category": "physical",
        "expected_unit": "ppt",
        "description": "Salt concentration of the water.",
        "threshold_profile": "salinity",
        "regulatory_source": "WHO",
        "warn_min": None,
        "warn_max": 0.5,
        "critical_min": None,
        "critical_max": 1.0,
        "alerts_enabled": False,
        "is_active": True,
    },
    {
        "parameter_code": "color",
        "display_name": "Color",
        "category": "physical",
        "expected_unit": "Pt-Co",
        "description": "Apparent color of water.",
        "threshold_profile": "color",
        "regulatory_source": "EPA",
        "warn_min": None,
        "warn_max": 15.0,
        "critical_min": None,
        "critical_max": 30.0,
        "alerts_enabled": False,
        "is_active": True,
    },
    {
        "parameter_code": "odor",
        "display_name": "Odor",
        "category": "physical",
        "expected_unit": "score",
        "description": "Sensory odor score for water quality screening.",
        "threshold_profile": "odor",
        "regulatory_source": "Operational",
        "warn_min": None,
        "warn_max": 3.0,
        "critical_min": None,
        "critical_max": 5.0,
        "alerts_enabled": False,
        "is_active": True,
    },
    {
        "parameter_code": "suspended_solids",
        "display_name": "Suspended Solids",
        "category": "physical",
        "expected_unit": "mg/L",
        "description": "Concentration of suspended solids in water.",
        "threshold_profile": "suspended_solids",
        "regulatory_source": "EPA/WHO",
        "warn_min": None,
        "warn_max": 25.0,
        "critical_min": None,
        "critical_max": 50.0,
        "alerts_enabled": False,
        "is_active": True,
    },
    {
        "parameter_code": "settleable_solids",
        "display_name": "Settleable Solids",
        "category": "physical",
        "expected_unit": "mL/L",
        "description": "Volume of solids that settle out of water over time.",
        "threshold_profile": "settleable_solids",
        "regulatory_source": "Operational",
        "warn_min": None,
        "warn_max": 1.0,
        "critical_min": None,
        "critical_max": 2.0,
        "alerts_enabled": False,
        "is_active": True,
    },
]