RADIOACTIVITY_PARAMETERS = [
    {
        "parameter_code": "gross_alpha_pci_l",
        "display_name": "Gross Alpha Radiation",
        "category": "radioactivity",
        "expected_unit": "pCi/L",
        "description": "Gross alpha particle activity in drinking water.",
        "threshold_profile": "gross_alpha_pci_l",
        "regulatory_source": "EPA",
        "warn_min": None,
        "warn_max": 12.0,
        "critical_min": None,
        "critical_max": 15.0,
        "alerts_enabled": True,
        "is_active": True,
    },
    {
        "parameter_code": "gross_beta_pci_l",
        "display_name": "Gross Beta Radiation",
        "category": "radioactivity",
        "expected_unit": "pCi/L",
        "description": "Gross beta particle activity in drinking water.",
        "threshold_profile": "gross_beta_pci_l",
        "regulatory_source": "EPA",
        "warn_min": None,
        "warn_max": 40.0,
        "critical_min": None,
        "critical_max": 50.0,
        "alerts_enabled": True,
        "is_active": True,
    },
    {
        "parameter_code": "radium226_pci_l",
        "display_name": "Radium-226",
        "category": "radioactivity",
        "expected_unit": "pCi/L",
        "description": "Naturally occurring radioactive radium isotope in groundwater.",
        "threshold_profile": "radium226_pci_l",
        "regulatory_source": "EPA",
        "warn_min": None,
        "warn_max": 4.0,
        "critical_min": None,
        "critical_max": 5.0,
        "alerts_enabled": True,
        "is_active": True,
    },
    {
        "parameter_code": "radium228_pci_l",
        "display_name": "Radium-228",
        "category": "radioactivity",
        "expected_unit": "pCi/L",
        "description": "Radium-228 isotope detected in groundwater sources.",
        "threshold_profile": "radium228_pci_l",
        "regulatory_source": "EPA",
        "warn_min": None,
        "warn_max": 4.0,
        "critical_min": None,
        "critical_max": 5.0,
        "alerts_enabled": True,
        "is_active": True,
    },
    {
        "parameter_code": "uranium_ug_l",
        "display_name": "Uranium",
        "category": "radioactivity",
        "expected_unit": "ug/L",
        "description": "Naturally occurring uranium in groundwater.",
        "threshold_profile": "uranium_ug_l",
        "regulatory_source": "EPA/WHO",
        "warn_min": None,
        "warn_max": 25.0,
        "critical_min": None,
        "critical_max": 30.0,
        "alerts_enabled": True,
        "is_active": True,
    },
    {
        "parameter_code": "radon_pci_l",
        "display_name": "Radon",
        "category": "radioactivity",
        "expected_unit": "pCi/L",
        "description": "Radon gas dissolved in groundwater.",
        "threshold_profile": "radon_pci_l",
        "regulatory_source": "EPA",
        "warn_min": None,
        "warn_max": 300.0,
        "critical_min": None,
        "critical_max": 400.0,
        "alerts_enabled": True,
        "is_active": True,
    },
]