SECONDARY_STANDARD_PARAMETERS = [
    {
        "parameter_code": "aluminum_mg_l",
        "display_name": "Aluminum",
        "category": "secondary_standard",
        "expected_unit": "mg/L",
        "description": "Secondary drinking water parameter affecting color and treatment performance.",
        "threshold_profile": "aluminum_mg_l",
        "regulatory_source": "EPA Secondary",
        "warn_min": None,
        "warn_max": 0.1,
        "critical_min": None,
        "critical_max": 0.2,
        "alerts_enabled": False,
        "is_active": True,
    },
    {
        "parameter_code": "chloride_mg_l",
        "display_name": "Chloride",
        "category": "secondary_standard",
        "expected_unit": "mg/L",
        "description": "Secondary standard affecting taste and corrosivity.",
        "threshold_profile": "chloride_mg_l",
        "regulatory_source": "EPA Secondary/WHO",
        "warn_min": None,
        "warn_max": 200.0,
        "critical_min": None,
        "critical_max": 250.0,
        "alerts_enabled": False,
        "is_active": True,
    },
    {
        "parameter_code": "copper_mg_l",
        "display_name": "Copper",
        "category": "secondary_standard",
        "expected_unit": "mg/L",
        "description": "Copper affecting taste, staining, and plumbing corrosion.",
        "threshold_profile": "copper_mg_l",
        "regulatory_source": "EPA Secondary",
        "warn_min": None,
        "warn_max": 0.8,
        "critical_min": None,
        "critical_max": 1.0,
        "alerts_enabled": False,
        "is_active": True,
    },
    {
        "parameter_code": "foaming_agents_mg_l",
        "display_name": "Foaming Agents",
        "category": "secondary_standard",
        "expected_unit": "mg/L",
        "description": "Synthetic detergents and foaming substances affecting taste and appearance.",
        "threshold_profile": "foaming_agents_mg_l",
        "regulatory_source": "EPA Secondary",
        "warn_min": None,
        "warn_max": 0.4,
        "critical_min": None,
        "critical_max": 0.5,
        "alerts_enabled": False,
        "is_active": True,
    },
    {
        "parameter_code": "iron_secondary_mg_l",
        "display_name": "Iron (Secondary)",
        "category": "secondary_standard",
        "expected_unit": "mg/L",
        "description": "Iron level affecting staining and taste.",
        "threshold_profile": "iron_secondary_mg_l",
        "regulatory_source": "EPA Secondary/WHO",
        "warn_min": None,
        "warn_max": 0.2,
        "critical_min": None,
        "critical_max": 0.3,
        "alerts_enabled": False,
        "is_active": True,
    },
    {
        "parameter_code": "manganese_secondary_mg_l",
        "display_name": "Manganese (Secondary)",
        "category": "secondary_standard",
        "expected_unit": "mg/L",
        "description": "Manganese affecting staining, taste, and appearance.",
        "threshold_profile": "manganese_secondary_mg_l",
        "regulatory_source": "EPA Secondary/WHO",
        "warn_min": None,
        "warn_max": 0.03,
        "critical_min": None,
        "critical_max": 0.05,
        "alerts_enabled": False,
        "is_active": True,
    },
    {
        "parameter_code": "silver_mg_l",
        "display_name": "Silver",
        "category": "secondary_standard",
        "expected_unit": "mg/L",
        "description": "Silver concentration in drinking water.",
        "threshold_profile": "silver_mg_l",
        "regulatory_source": "EPA Secondary",
        "warn_min": None,
        "warn_max": 0.08,
        "critical_min": None,
        "critical_max": 0.1,
        "alerts_enabled": False,
        "is_active": True,
    },
    {
        "parameter_code": "sulfate_secondary_mg_l",
        "display_name": "Sulfate (Secondary)",
        "category": "secondary_standard",
        "expected_unit": "mg/L",
        "description": "Sulfate affecting taste and possible laxative effects.",
        "threshold_profile": "sulfate_secondary_mg_l",
        "regulatory_source": "EPA Secondary/WHO",
        "warn_min": None,
        "warn_max": 200.0,
        "critical_min": None,
        "critical_max": 250.0,
        "alerts_enabled": False,
        "is_active": True,
    },
    {
        "parameter_code": "zinc_mg_l",
        "display_name": "Zinc",
        "category": "secondary_standard",
        "expected_unit": "mg/L",
        "description": "Zinc concentration affecting taste.",
        "threshold_profile": "zinc_mg_l",
        "regulatory_source": "EPA Secondary/WHO",
        "warn_min": None,
        "warn_max": 4.0,
        "critical_min": None,
        "critical_max": 5.0,
        "alerts_enabled": False,
        "is_active": True,
    },
]