"""add normalized_water_records table

Revision ID: 380c34d328f7
Revises: 25a289fcba18
Create Date: 2026-03-17 08:49:40.571310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '380c34d328f7'
down_revision: Union[str, Sequence[str], None] = '25a289fcba18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_sources_id'), table_name='data_sources')
    op.drop_table('data_sources')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('source_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('organization_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('source_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('endpoint_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('auth_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('parser_type', sa.VARCHAR(length=50), server_default=sa.text("'generic'::character varying"), autoincrement=False, nullable=False),
    sa.Column('refresh_interval_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('region', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('county', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('default_location_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('data_sources_created_by_user_id_fkey')),
    sa.ForeignKeyConstraint(['default_location_id'], ['locations.id'], name=op.f('data_sources_default_location_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('data_sources_pkey'))
    )
    op.create_index(op.f('ix_data_sources_id'), 'data_sources', ['id'], unique=False)
    # ### end Alembic commands ###
