"""add alert delivery logs

Revision ID: 3f58ceca9491
Revises: 5d96807df797
Create Date: 2026-03-21 21:58:43.860045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f58ceca9491'
down_revision: Union[str, Sequence[str], None] = '5d96807df797'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_delivery_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('parameter_code', sa.String(length=64), nullable=False),
    sa.Column('escalation_level', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('recipient_target', sa.String(length=255), nullable=False),
    sa.Column('delivery_status', sa.String(length=32), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_delivery_logs_id'), 'alert_delivery_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_delivery_logs_id'), table_name='alert_delivery_logs')
    op.drop_table('alert_delivery_logs')
    # ### end Alembic commands ###
