"""add threshold fields to parameter_definitions

Revision ID: 5a9a8d725829
Revises: 5ffce1020786
Create Date: 2026-03-12 19:09:16.502652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a9a8d725829'
down_revision: Union[str, Sequence[str], None] = '5ffce1020786'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_subscriptions_scope'), table_name='alert_subscriptions')
    op.drop_table('alert_subscriptions')
    op.drop_index(op.f('idx_alerts_cluster'), table_name='alerts')
    op.drop_index(op.f('idx_alerts_country'), table_name='alerts')
    op.drop_index(op.f('idx_alerts_county'), table_name='alerts')
    op.drop_index(op.f('idx_alerts_region'), table_name='alerts')
    op.drop_index(op.f('idx_alerts_state'), table_name='alerts')
    op.drop_index(op.f('idx_alerts_status_sent'), table_name='alerts')
    op.add_column('parameter_definitions', sa.Column('regulatory_source', sa.String(length=64), nullable=True))
    op.add_column('parameter_definitions', sa.Column('warn_min', sa.Float(), nullable=True))
    op.add_column('parameter_definitions', sa.Column('warn_max', sa.Float(), nullable=True))
    op.add_column('parameter_definitions', sa.Column('critical_min', sa.Float(), nullable=True))
    op.add_column('parameter_definitions', sa.Column('critical_max', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parameter_definitions', 'critical_max')
    op.drop_column('parameter_definitions', 'critical_min')
    op.drop_column('parameter_definitions', 'warn_max')
    op.drop_column('parameter_definitions', 'warn_min')
    op.drop_column('parameter_definitions', 'regulatory_source')
    op.create_index(op.f('idx_alerts_status_sent'), 'alerts', ['status', sa.literal_column('sent_at DESC')], unique=False)
    op.create_index(op.f('idx_alerts_state'), 'alerts', ['state_region'], unique=False)
    op.create_index(op.f('idx_alerts_region'), 'alerts', ['region_code'], unique=False)
    op.create_index(op.f('idx_alerts_county'), 'alerts', ['county_code'], unique=False)
    op.create_index(op.f('idx_alerts_country'), 'alerts', ['country'], unique=False)
    op.create_index(op.f('idx_alerts_cluster'), 'alerts', ['cluster_code'], unique=False)
    op.create_table('alert_subscriptions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('subscriber_type', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('subscriber_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('scope_type', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('scope_code', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('delivery_channel', sa.VARCHAR(length=16), server_default=sa.text("'in_app'::character varying"), autoincrement=False, nullable=False),
    sa.Column('recipient', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('alert_subscriptions_pkey'))
    )
    op.create_index(op.f('ix_alert_subscriptions_scope'), 'alert_subscriptions', ['scope_type', 'scope_code'], unique=False)
    # ### end Alembic commands ###
