"""add central systems and distribution lines

Revision ID: 5d96807df797
Revises: de4cf15efc3c
Create Date: 2026-03-19 17:57:19.137710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d96807df797'
down_revision: Union[str, Sequence[str], None] = 'de4cf15efc3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('central_systems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_central_systems_code'), 'central_systems', ['code'], unique=True)
    op.create_index(op.f('ix_central_systems_id'), 'central_systems', ['id'], unique=False)
    op.create_table('distribution_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('central_system_id', sa.Integer(), nullable=False),
    sa.Column('line_code', sa.String(length=64), nullable=False),
    sa.Column('line_name', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['central_system_id'], ['central_systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_distribution_lines_central_system_id'), 'distribution_lines', ['central_system_id'], unique=False)
    op.create_index(op.f('ix_distribution_lines_id'), 'distribution_lines', ['id'], unique=False)
    op.create_index(op.f('ix_distribution_lines_line_code'), 'distribution_lines', ['line_code'], unique=True)
    op.drop_index(op.f('ix_raw_water_records_id'), table_name='raw_water_records')
    op.drop_table('raw_water_records')
    op.add_column('locations', sa.Column('central_system_id', sa.Integer(), nullable=True))
    op.add_column('locations', sa.Column('distribution_line_id', sa.Integer(), nullable=True))
    op.add_column('locations', sa.Column('state', sa.String(length=64), nullable=True))
    op.add_column('locations', sa.Column('county', sa.String(length=64), nullable=True))
    op.add_column('locations', sa.Column('x', sa.Integer(), nullable=True))
    op.add_column('locations', sa.Column('y', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'locations', 'central_systems', ['central_system_id'], ['id'])
    op.create_foreign_key(None, 'locations', 'distribution_lines', ['distribution_line_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'locations', type_='foreignkey')
    op.drop_constraint(None, 'locations', type_='foreignkey')
    op.drop_column('locations', 'y')
    op.drop_column('locations', 'x')
    op.drop_column('locations', 'county')
    op.drop_column('locations', 'state')
    op.drop_column('locations', 'distribution_line_id')
    op.drop_column('locations', 'central_system_id')
    op.create_table('raw_water_records',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ingestion_run_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('external_record_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('parsing_status', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('raw_water_records_pkey'))
    )
    op.create_index(op.f('ix_raw_water_records_id'), 'raw_water_records', ['id'], unique=False)
    op.drop_index(op.f('ix_distribution_lines_line_code'), table_name='distribution_lines')
    op.drop_index(op.f('ix_distribution_lines_id'), table_name='distribution_lines')
    op.drop_index(op.f('ix_distribution_lines_central_system_id'), table_name='distribution_lines')
    op.drop_table('distribution_lines')
    op.drop_index(op.f('ix_central_systems_id'), table_name='central_systems')
    op.drop_index(op.f('ix_central_systems_code'), table_name='central_systems')
    op.drop_table('central_systems')
    # ### end Alembic commands ###
