"""add continuous ingestion core tables

Revision ID: c18f81886737
Revises: 807139cdc3c5
Create Date: 2026-03-22 14:48:59.180262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c18f81886737'
down_revision: Union[str, Sequence[str], None] = '807139cdc3c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_alert_delivery_logs_delivery_status'), 'alert_delivery_logs', ['delivery_status'], unique=False)
    op.create_index(op.f('ix_alert_delivery_logs_escalation_level'), 'alert_delivery_logs', ['escalation_level'], unique=False)
    op.create_index(op.f('ix_alert_delivery_logs_parameter_code'), 'alert_delivery_logs', ['parameter_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_delivery_logs_parameter_code'), table_name='alert_delivery_logs')
    op.drop_index(op.f('ix_alert_delivery_logs_escalation_level'), table_name='alert_delivery_logs')
    op.drop_index(op.f('ix_alert_delivery_logs_delivery_status'), table_name='alert_delivery_logs')
    # ### end Alembic commands ###
